### ISSUE TITLE
Obj/Collada models fall through with dynamic/static-body

### ISSUE THREAD

**Issue by Anjlo** [c-frame/aframe-extras#41]
Test at http://anj.fyi/mountains

The manatee falls through the floor, and the mountain mesh isn't walkable.

Link to models:
http://anj.fyi/images/manatee.obj
http://anj.fyi/images/mountains.dae

**Comment by donmccurdy** [comment]
Alright, two issues –

The first is general trimesh support, mentioned in schteppe/cannon.js#231 and schteppe/cannon.js#191. In summary, collisions on a trimesh are not as fully supported as other shapes. I've got a demo working that uses a trimesh as the ground, and the player (a sphere) can sort of walk across it, buggily, but cubes can't collide with a trimesh yet. Similarly, the (trimesh) manatee will fall through the (cube-ish) floor.

My ideas are:
1. Provide an option to wrap a bounding box around the model, in case that's enough for your use case (for a manatee, that seems fine).
2. Add support (in my components) for CANNON.Heightfield shapes, which _might_ take care of the terrain examples, if I can reasonably convert a BufferGeometry to a heightmap.
3. Later, provide some declarative API for creating compound shapes – of multiple cubes/spheres/etc – which is the preferred method of doing collisions on a complex shape, anyway.
4. Also later, see about sending a PR to Cannon.js with additional trimesh collision support.

I can add 1 pretty soon. 2-4 are more difficult, so no promises on timeline there. PRs welcome!

/cc @bnolan and @h0r0man, since we've discussed issues with trimesh collision a bit.

---

##### EDIT –

CANNON.js gives much more detail into support for various shapes in the [collision matrix](https://github.com/schteppe/cannon.js/blob/master/README.markdown#features).

**Comment by donmccurdy** [comment]
Second issue, that mountain mesh is pretty complex to just throw at a JS physics engine. Here's the wireframe coming out of it all:

![screen shot 2016-05-04 at 10 46 07 pm](https://cloud.githubusercontent.com/assets/1848368/15035066/1df7cd3c-124b-11e6-82a5-046bd5a1563e.png)

Clearly that's not, eh, working quite as expected. Maybe best not to have the whole scene in one big model – much easier for the physics engine if each tree can just be modeled as a box, and terrain as a heightmap, than one massive mesh.

So 1-4 above will give you some options to work with, but it won't be able to magically physics-ify any arbitrary model, I don't think.

**Comment by wizgrav** [comment]
maybe I'm way off here but maybe you could ortho render the terrain from above at low resolution and take it's depth as the heightmap

**Comment by donmccurdy** [comment]
@wizgrav yeah, sounds feasible but a bit painful. raycasting at some sampling ratio would work too, but slower. 😐

**Comment by donmccurdy** [comment]
Well here's a start on (1), in v1.13.0. Not documented yet because various bugs, but –

``` html
<a-entity obj-model="obj: url(...)" dynamic-body="shape: box"></a-entity>
```

Which will ignore the actual shape of the mesh and just put a box around it. You can see the bounding box by adding `physics="debug: true"` to the `<a-scene/>`.

Also, CANNON.js gives quite a bit more detail into what's supported in its [collision matrix](https://github.com/schteppe/cannon.js/blob/master/README.markdown#features).

**Comment by wizgrav** [comment]
@donmccurdy yeah raycasting is much more practical and the overhead is not necessarily prohibitive, maybe an octree could be generated to speed up the process and could also be useful for generic intersection testing later.

**Comment by h0r0m4n** [comment]
@donmccurdy Hi, the `#player` is getting stick to the ground and after few moves it’s falling down:
![qui-vid](https://cloud.githubusercontent.com/assets/2571888/15096673/f2929422-1503-11e6-8caf-4c41337ecb71.gif)

I’m trying to use simple ground `.obj` with `.mtl`. here’s a preview of 3d model, it’ a basic plane subdivided by ~256 cuts:
<img width="1205" alt="screen shot 2016-05-08 at 10 00 37" src="https://cloud.githubusercontent.com/assets/2571888/15096664/c0d15e78-1503-11e6-93b3-bffa05f4d01a.png">

Here is how is rendered:
<img width="777" alt="screen shot 2016-05-08 at 10 11 58" src="https://cloud.githubusercontent.com/assets/2571888/15096700/60dbad50-1505-11e6-80fe-4cd3cda1b741.png">

Here’s a html:

``` html
<!-- aframe v0.2.0 & aframe-extras v1.14.0 -->
<a-scene physics="debug:true">
  <a-entity
    id="player"
    camera
    universal-controls
    kinematic-body="enableSlopes: false"
    position="0 4 2"></a-entity>
  <a-entity
    id="scene"
    static-body
    obj-model="obj: url(object/ground.obj); mtl: url(object/ground.mtl);"></a-entity>
</a-scene>
```

**Comment by donmccurdy** [comment]
Oh nice documentation on that! Thanks.
Working on this a bit, it (gradually falling through the floor) should be mostly solved with v1.14.1 now.

**Comment by h0r0m4n** [comment]
@donmccurdy After v1.13.0 if use [collada-model](https://aframe.io/docs/components/collada-model.html) it’s basically freezes the browser!

``` html
<a-entity collada-model="url(/path/to/tree.dae)"></a-entity>
```

**Comment by donmccurdy** [comment]
☹️ hm. @h0r0man did it work with your OBJ example but start locking up on a DAE? could you post a demo or link to that DAE model?

**Comment by h0r0m4n** [comment]
@donmccurdy Here’s a [simple pen](http://codepen.io/horoman/pen/dMrXgP?editors=1000), just try to remove an HTML comment to use your library.

**Comment by donmccurdy** [comment]
Great thanks. Hoping I can get to this tomorrow, the most likely issue is mesh -> physics body conversion. There's a case where it can enter an infinite loop.

**Comment by donmccurdy** [comment]
Some progress in 9df3943a4cae721057fa846435946171406fae3b (not released yet). I think the main issue with that Collada model is solved, but there's an issue that causes the physics body to not scale to match the model. Still working on that.

**Comment by h0r0m4n** [comment]
Hi, the main problem of collisions with Cannon, isn't resolved yet, even with such a primitive 3D models like `monu9.obj`:

![bug-falling](https://cloud.githubusercontent.com/assets/2571888/15257243/b4adea4e-1945-11e6-8dd5-9f6297aa6d43.gif)

**Comment by donmccurdy** [comment]
@h0r0man ah yeah, no I just fixed the collada freezing issue so far. using an arbitrary mesh as ground is likely to have issues for a while, not least because lots of shapes can't collide with a trimesh in cannonjs (or oimojs for that matter). i'd like to focus on roomscale tbh. 

i think next on my list though is (3) above, to let you define compound shapes around a model using multiple cubes/cylinders. that way even if your model isn't supported you can at least put a custom frame around it (e.g. to pick it up or toss it around)

**Comment by donmccurdy** [comment]
Added `shape: hull`, and better support for the (much faster) `shape: box` option. [Documentation here](https://github.com/donmccurdy/aframe-extras/blob/master/src/physics/README.md#body-shapes). Those should be helpful for props and obstacles, but probably not terrain.

**Comment by h0r0man** [comment]
@donmccurdy Awesome I give a look tomorrow!

**Comment by donmccurdy** [comment]
Moving this discussion over to https://github.com/donmccurdy/aframe-physics-system/issues/9, and I've added a brief summary there.
